spring:
  datasource:
    url: jdbc:mysql://133.186.241.167:3306/nhn_academy_23
    username: nhn_academy_23
    password: o5.WNs/X5Fb*NQ5K
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    properties:
      hibernate:
        auto_quote_keyword: true
        highlight_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB