spring:
  datasource:
    url: jdbc:mysql://133.186.241.167:3306/be6_codequest
    username: be6_codequest
    password: 2n[vFtM)vLCmAjxR
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    properties:
      hibernate:
        auto_quote_keyword: true
        highlight_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8008/eureka
    fetch-registry: true
  instance:
    ip-address: true

