server:
  port: 8008

spring:
  application:
    name: orderPaymentRefund
  profiles:
    active: heewon

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8002/eureka
    fetch-registry: true
  instance:
    ip-address: true