server:
  port: 8008

spring:
  application:
    name: codequest_order_payment_refund
  profiles:
    active: prod

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8002/eureka
    fetch-registry: true
  instance:
    ip-address: true