### GET request to example server
GET http://localhost:8008/api/refund?orderId=160

###

### post
POST /v1/payments/{paymentKey/cancel


### 반품요청
GET localhost:8008/api/refund/request?orderId=319

### 취소
POST localhost:8008/api/refund/cancel?orderId
Content-Type: application/json

{"orderStatus": "결제완료",
"orderId": 312}